format = "ğŸ³ $all"

[username]
format = "[$user](dim)"
show_always = true

[hostname]
format = "[@$hostname](bold green) "
ssh_only = false

[memory_usage]
style = "dimmed"
disabled = false
threshold = -1
format = "[${ram_pct}]($style) "
