# ~/.config/starship.toml

format = "ğŸ³ $all"

[username]
style_root = "magenta bold"
style_user = "green bold"
format = "[$user]($style)"
show_always = true

[hostname]
format = "[@$hostname](bold green) "
ssh_only = false

[memory_usage]
style = "dimmed"
disabled = false
threshold = -1
format = "[${ram}]($style) "
